
package
{
	
	public final class LevelData
	{
		
		// Level 1 Data
		public static const level1Obstacles:Array = [C.OBSTACLE_TYPE_ROCK, 200, 300,
															C.OBSTACLE_TYPE_ROCK, 500, 600,
															C.OBSTACLE_TYPE_TREE, 400, 100,
															C.OBSTACLE_TYPE_TREE, 200, 150,
															C.OBSTACLE_TYPE_TREE, 800, 500,
															C.OBSTACLE_TYPE_TREE, 1100, 200,
															C.OBSTACLE_TYPE_TREE, 300, 600,
															C.OBSTACLE_TYPE_TREE, 1200, 550,
															C.OBSTACLE_TYPE_ROCK, 600, 300,
															C.OBSTACLE_TYPE_ROCK, 800, 350,
															C.OBSTACLE_TYPE_ROCK, 700, 100,
															C.OBSTACLE_TYPE_ROCK, 1150, 700];
		public static const level1PreyTargets:Array = [C.PREY_TYPE_GAZELLE,
													   C.PREY_TYPE_GAZELLE,
													   C.PREY_TYPE_GAZELLE, 
													   C.PREY_TYPE_GAZELLE,
													   C.PREY_TYPE_GAZELLE, 
													   C.PREY_TYPE_GAZELLE,
													   C.PREY_TYPE_GAZELLE, 
													   C.PREY_TYPE_GAZELLE,
													   C.PREY_TYPE_GAZELLE, 
													   C.PREY_TYPE_GAZELLE];
		
		
		// Level 2 Data 
		public static const level2Obstacles:Array = [C.OBSTACLE_TYPE_ROCK, 500, 470,
															C.OBSTACLE_TYPE_ROCK, 1050, 200,
															C.OBSTACLE_TYPE_ROCK, 400, 600,
															C.OBSTACLE_TYPE_ROCK, 450, 400,
															C.OBSTACLE_TYPE_ROCK, 800, 550,
															C.OBSTACLE_TYPE_ROCK, 1200, 620,
															C.OBSTACLE_TYPE_ROCK, 250, 250,
															C.OBSTACLE_TYPE_TREE, 900, 150,
															C.OBSTACLE_TYPE_TREE, 1150, 400,
															C.OBSTACLE_TYPE_TREE, 300, 500,
															C.OBSTACLE_TYPE_TREE, 500, 300,
															C.OBSTACLE_TYPE_TREE, 700, 625,
															C.OBSTACLE_TYPE_TREE, 1300, 250,
															C.OBSTACLE_TYPE_TREE, 50, 120,
															C.OBSTACLE_TYPE_TREE, 150, 725];
		public static const level2PreyTargets:Array = [C.PREY_TYPE_GAZELLE,
													   C.PREY_TYPE_GAZELLE,
													   C.PREY_TYPE_GAZELLE, 
													   C.PREY_TYPE_GAZELLE,
													   C.PREY_TYPE_GAZELLE, 
													   C.PREY_TYPE_GAZELLE,
													   C.PREY_TYPE_GAZELLE, 
													   C.PREY_TYPE_GAZELLE,
													   C.PREY_TYPE_GAZELLE, 
													   C.PREY_TYPE_GAZELLE];
		
		public static const level3Obstacles:Array = [C.OBSTACLE_TYPE_WATER, 800, 200,
															C.OBSTACLE_TYPE_ROCK, 900, 200,
															C.OBSTACLE_TYPE_ROCK, 500, 120,
															C.OBSTACLE_TYPE_ROCK, 50, 600,
															C.OBSTACLE_TYPE_TREE, 500, 500,
															C.OBSTACLE_TYPE_TREE, 1000, 100,
															C.OBSTACLE_TYPE_TREE, 950, 600,
															C.OBSTACLE_TYPE_TREE, 200, 300,
															C.OBSTACLE_TYPE_TREE, 600, 300,
															C.OBSTACLE_TYPE_WATER, 150, 600,
															C.OBSTACLE_TYPE_TREE, 400, 100];
		public static const level3PreyTargets:Array = [C.PREY_TYPE_GAZELLE,
													   C.PREY_TYPE_GAZELLE,
													   C.PREY_TYPE_GAZELLE, 
													   C.PREY_TYPE_GAZELLE,
													   C.PREY_TYPE_GAZELLE, 
													   C.PREY_TYPE_GAZELLE,
													   C.PREY_TYPE_GAZELLE, 
													   C.PREY_TYPE_GAZELLE,
													   C.PREY_TYPE_HIPPO, 
													   C.PREY_TYPE_HIPPO];
		
		public static const level4Obstacles:Array = [C.OBSTACLE_TYPE_ROCK, 500, 300,
															C.OBSTACLE_TYPE_ROCK, 500, 60,
															C.OBSTACLE_TYPE_ROCK, 60, 600,
															C.OBSTACLE_TYPE_ROCK, 175, 400,
															C.OBSTACLE_TYPE_ROCK, 175, 250,
															C.OBSTACLE_TYPE_ROCK, 175, 300,
															C.OBSTACLE_TYPE_ROCK, 175, 350,
															C.OBSTACLE_TYPE_ROCK, 175, 450,
															C.OBSTACLE_TYPE_ROCK, 175, 500,
															C.OBSTACLE_TYPE_ROCK, 175, 550,
															C.OBSTACLE_TYPE_ROCK, 1225, 400,
															C.OBSTACLE_TYPE_ROCK, 1225, 250,
															C.OBSTACLE_TYPE_ROCK, 1225, 300,
															C.OBSTACLE_TYPE_ROCK, 1225, 350,
															C.OBSTACLE_TYPE_ROCK, 1225, 450,
															C.OBSTACLE_TYPE_ROCK, 1225, 500,
															C.OBSTACLE_TYPE_ROCK, 1225, 550,
															C.OBSTACLE_TYPE_TREE, 1225, 125,
															C.OBSTACLE_TYPE_TREE, 120, 500,
															C.OBSTACLE_TYPE_TREE, 400, 750,
															C.OBSTACLE_TYPE_TREE, 150, 150,
															C.OBSTACLE_TYPE_TREE, 1000, 650,
															C.OBSTACLE_TYPE_WATER, 720, 250,
															C.OBSTACLE_TYPE_WATER, 270, 250,];
		public static const level4PreyTargets:Array = [C.PREY_TYPE_GAZELLE,
													   C.PREY_TYPE_GAZELLE,
													   C.PREY_TYPE_GAZELLE, 
													   C.PREY_TYPE_GAZELLE,
													   C.PREY_TYPE_GAZELLE, 
													   C.PREY_TYPE_HIPPO,
													   C.PREY_TYPE_HIPPO, 
													   C.PREY_TYPE_HIPPO,
													   C.PREY_TYPE_HIPPO, 
													   C.PREY_TYPE_HIPPO,
													   C.PREY_TYPE_HIPPO,
													   C.PREY_TYPE_HIPPO];
															
		public static const level5Obstacles:Array = [C.OBSTACLE_TYPE_ROCK, 500, 350,
															C.OBSTACLE_TYPE_ROCK, 820, 600,
															C.OBSTACLE_TYPE_ROCK, 50, 600,
															C.OBSTACLE_TYPE_TREE, 200, 200,
															C.OBSTACLE_TYPE_TREE, 1020, 300,
															C.OBSTACLE_TYPE_TREE, 500, 260,
															C.OBSTACLE_TYPE_TREE, 570, 240,
															C.OBSTACLE_TYPE_TREE, 650, 270,
															C.OBSTACLE_TYPE_TREE, 720, 230,
															C.OBSTACLE_TYPE_TREE, 770, 280,
															C.OBSTACLE_TYPE_TREE, 840, 240,
															C.OBSTACLE_TYPE_TREE, 870, 275,
															C.OBSTACLE_TYPE_TREE, 940, 250,
															C.OBSTACLE_TYPE_TREE, 500, 660,
															C.OBSTACLE_TYPE_TREE, 570, 640,
															C.OBSTACLE_TYPE_TREE, 650, 670,
															C.OBSTACLE_TYPE_TREE, 720, 630,
															C.OBSTACLE_TYPE_TREE, 770, 670,
															C.OBSTACLE_TYPE_TREE, 840, 640,
															C.OBSTACLE_TYPE_TREE, 870, 675,
															C.OBSTACLE_TYPE_TREE, 940, 650,
															C.OBSTACLE_TYPE_WATER, 1050, 325];
															
		public static const level5PreyTargets:Array = [C.PREY_TYPE_GAZELLE];
	}
}